
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:58 (PROJECT)"
    message: |
      The system is: Windows - 10.0.22635 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:58 (PROJECT)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 2023/11/6 0:12:28。
      
      节点 1 上的项目“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\3.28.0-rc3\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\3.28.0-rc3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\3.28.0-rc3\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.50
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/3.28.0-rc3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:58 (PROJECT)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/GR;/EHsc
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 2023/11/6 0:12:30。
      
      节点 1 上的项目“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\3.28.0-rc3\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\3.28.0-rc3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\3.28.0-rc3\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.34
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/3.28.0-rc3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/cmake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:58 (PROJECT)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-exz7o0"
      binary: "D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-exz7o0"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-exz7o0'
        
        Run Build Command(s): "F:/Visual Studio 2022/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_46f97.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 2023/11/6 0:12:32。
        
        节点 1 上的项目“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-exz7o0\\cmTC_46f97.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_46f97.dir\\Debug\\”。
          正在创建目录“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-exz7o0\\Debug\\”。
          正在创建目录“cmTC_46f97.dir\\Debug\\cmTC_46f97.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_46f97.dir\\Debug\\cmTC_46f97.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_46f97.dir\\Debug\\cmTC_46f97.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_46f97.dir\\Debug\\\\" /Fd"cmTC_46f97.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "D:\\cmake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32824 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_46f97.dir\\Debug\\\\" /Fd"cmTC_46f97.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "D:\\cmake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-exz7o0\\Debug\\cmTC_46f97.exe" /INCREMENTAL /ILK:"cmTC_46f97.dir\\Debug\\cmTC_46f97.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-exz7o0/Debug/cmTC_46f97.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-exz7o0/Debug/cmTC_46f97.lib" /MACHINE:X64  /machine:x64 cmTC_46f97.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_46f97.vcxproj -> D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-exz7o0\\Debug\\cmTC_46f97.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_46f97.dir\\Debug\\cmTC_46f97.tlog\\unsuccessfulbuild”。
          正在对“cmTC_46f97.dir\\Debug\\cmTC_46f97.tlog\\cmTC_46f97.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-exz7o0\\cmTC_46f97.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.34
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/cmake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:58 (PROJECT)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-ujio1x"
      binary: "D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-ujio1x"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-ujio1x'
        
        Run Build Command(s): "F:/Visual Studio 2022/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_efb94.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 2023/11/6 0:12:34。
        
        节点 1 上的项目“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-ujio1x\\cmTC_efb94.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_efb94.dir\\Debug\\”。
          正在创建目录“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-ujio1x\\Debug\\”。
          正在创建目录“cmTC_efb94.dir\\Debug\\cmTC_efb94.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_efb94.dir\\Debug\\cmTC_efb94.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_efb94.dir\\Debug\\cmTC_efb94.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_efb94.dir\\Debug\\\\" /Fd"cmTC_efb94.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\cmake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32824 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_efb94.dir\\Debug\\\\" /Fd"cmTC_efb94.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\cmake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          F:\\Visual Studio 2022\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-ujio1x\\Debug\\cmTC_efb94.exe" /INCREMENTAL /ILK:"cmTC_efb94.dir\\Debug\\cmTC_efb94.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-ujio1x/Debug/cmTC_efb94.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Assimp/assimp-master/assimp-master/BUILD/CMakeFiles/CMakeScratch/TryCompile-ujio1x/Debug/cmTC_efb94.lib" /MACHINE:X64  /machine:x64 cmTC_efb94.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_efb94.vcxproj -> D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-ujio1x\\Debug\\cmTC_efb94.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_efb94.dir\\Debug\\cmTC_efb94.tlog\\unsuccessfulbuild”。
          正在对“cmTC_efb94.dir\\Debug\\cmTC_efb94.tlog\\cmTC_efb94.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\Assimp\\assimp-master\\assimp-master\\BUILD\\CMakeFiles\\CMakeScratch\\TryCompile-ujio1x\\cmTC_efb94.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.33
        
      exitCode: 0
...
